input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][index]" => "novahub-%{+YYYY.MM.dd}" }
    }
  }

  if [level] == "ERROR" {
    mutate {
      add_tag => [ "error" ]
    }
  }

  date {
    match => [ "@timestamp", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => [ "elasticsearch:9200" ]
    index => "%{[@metadata][index]}"
  }
}
